[en.core]
shop = "<s>The shop is not currently available."
whitelist = "<s>You are not whitelisted."
welcome = """

        <s>Welcome to <p>Airbrush</p>, <p>%s</p>!

        <s>To paint, <p>right-click</p> with the <p>Paintbrush</p>
        <s>To select a block to paint with, <p>left-click</p> with the <p>Paintbrush</p>

"""
broadcasts = """
        <br><p>Airbrush <g>- <s>If you enjoyed the server, be sure to <y><u>/fav</u></y> it!<br>
        <br><p>Airbrush <g>- <s>Join our Discord server with <click:open_url:https://discord.gg/yAgCb9AHM8><#7289da><u>/discord</click><br>
"""

[en.core.leveling]
level_up = "<s>You have leveled up to <p>level %s</p>!"
new_block = "<s>You have unlocked the <p>%s</p> block palette!"

[en.core.brush_gui]
title = "Brush Settings"
item_lore = "<#fcd1e0>â€¢ Click to select!"
decrease_size = "<p>Decrease brush size"
increase_size = "<p>Increase brush size"
locked_radius = "<s>You haven't unlocked a radius of <p>%s</p> yet."
set_block = "<s>You have chosen <p>%s</p>."

[en.core.select_palette]
title = "Select Palette"
item = "%s"
progression_success = "<s>You are now progressing in the <p>%s</p> palette."
set_palette = "<s>You are now using the <p>%s</p> palette."

[en.core.items]
eyedropper = "Eyedropper"
palette_selector = "Palette Selector"
paintbrush = "Paintbrush"
main_menu = "Main Menu"

[en.core.notifications]
join = "<s>[<g>+</g>] <p>%s"
leave = "<s>[<color:#f16c6c>-</color>] <p>%s"

[en.core.scoreboard]
title = "<b><#cd1a15>A<#f84600>i<#f87d00>r<#f8c300>b<#12b304>r<#2d2ff8>u<#7711d8>s<#c111d8>h</b>"
level = "<s>Level: %s"
exp = "<s>XP: <p>%s</p>/<p>%s"
rank = "<s>Rank: <p>%s"
world = "<s>World: <g>%s"

[en.punishments]
punishment = "<gray><p>%moderator%</p> %type% <p>%player%</p> - <red>%short_reason%</red> [%duration_uppercase%]"
kickedPlayer = "<gray><p>%moderator%</p> %type% <p>%player%</p> - <red>%short_reason%</red>"
reversion = "<gray><p>%moderator%</p> reverted the punishment of <p>%player%</p>."
playerMuted = """
        <s>%long_reason%. Expires in <p>%duration_lowercase%</p>.

        <s>Think this is a mistake? Join our <click:open_url:https://discord.gg/yAgCb9AHM8><#7289da><u>here</u></click><s> to appeal.
"""
playerBanned = """
        <p>Banned from</p> %title%.

        <s>%long_reason%

        <s>Think this is a mistake? Join https://discord.gg/yAgCb9AHM8 to appeal.
"""
playerKicked = """
        <p>Kicked from</p> %title%.

        <s>%long_reason%
"""

[en.core.commands]
discord = "<s>You can join our discord server <click:open_url:https://discord.gg/yHnenrHnsQ><p>here</p>."
gamemode = "<s>You are now in <p>%s mode</p>."
clearchat = "<s>Chat has been cleared."
lockdown = "<s>Lockdown has been %s."
radius = "<s>Your radius has been set to <p>%s</p>."
staff_chat = "<p>[S] %s<s>: %s"
vanish = "<s>You are now %s."
tiny = { true = "<s>You are now tiny!", false = "<s>You are no longer tiny ;c" }
palette = { message = "<s>Set your palette to <p>%s</p>." }

[en.core.commands.mask]
set = "<s>You have set your mask to <p>%s</p>."
none = "<s>You don't have a mask set."
clear = "<s>Your mask has been cleared."
view = "<s>Your current mask is <p>%s</p>."
alert = "<s>You currently have a <p>%s</p> mask enabled."

[en.core.commands.rules]
overview = """
        <b>1.</b> Be respectful
        <b>2.</b> No NSFW content
        <b>3.</b> Threats are not welcome
        <b>4.</b> No advertisements
        <b>5.</b> No griefing or trolling

        <#19911d>For further info, continue reading >
"""
rule1 = """
        <b>1. Be respectful</b>

        Discrimination in any form is not tolerated anywhere on Airbrush.
        Being disrespectful to others, instigating arguments, attacking
        people especially for no reason are also not welcome.
"""
rule2 = """
        <b>2. No NSFW content</b>

        NSFW topics or themes are not allowed in neither chat nor paint.
        Politics are discouraged as it is a near guarantee of turning hostile.
"""
rule3 = """
        <b>3. Threats are not welcome</b>

        This includes any sort of threat, joke or not. Attempts will also be reported to Minehut themselves.
"""
rule4 = """
        <b>4. No advertising</b>

        Please do not advertise other servers, Discord servers, websites, etc.
"""
rule5 = """
        <b>5. No griefing or trolling</b>

        If someone is painting something, try to not disturb and paint elsewhere.
        If you are only here to troll, harass, needlessly grief, etc. there is no reason
        for your presence.
"""