botToken = "" # Discord bot token to be used for chat

linkRequest = "<newline><#82a9ce>%username%<#bfdefb> requested to link their Discord<newline><#bffbdb><hover:show_text:'<#ffd4e3><i>Click to approve'><click:run_command:/link accept %sessionId%>✔ Accept </click><gray>| <#fbcebf><hover:show_text:'<#ffd4e3><i>Click to deny'><click:run_command:/link deny %sessionId%>✗ Deny</click><newline>"

[channels]
main = "" # Main chat channel ID
log = "" # Log channel ID

[join]
content = "`[%timestamp%] %name% joined`"
[leave]
content = "`[%timestamp%] %name% left`"
[chat]
content = "`[%timestamp%] %rank% %name%: %message%`"
[ingame]
content = "<s>[#] <p>%name%</p>: %message%"